// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSync.Infraestructure.Persistence.Context;

#nullable disable

namespace SmartSync.Infraestructure.Migrations
{
    [DbContext(typeof(SmartSyncDbContext))]
    partial class SmartSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SmartSync.Domain.Entities.Comodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResidenciaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResidenciaId");

                    b.ToTable("Comodos");
                });

            modelBuilder.Entity("SmartSync.Domain.Entities.Dispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComodoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TipoDispositivoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComodoId");

                    b.HasIndex("TipoDispositivoId");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("SmartSync.Domain.Entities.Residencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Residencias");
                });

            modelBuilder.Entity("SmartSync.Domain.Entities.TipoDispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Acoes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TipoDispositivos");
                });

            modelBuilder.Entity("SmartSync.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SmartSync.Domain.Entities.Comodo", b =>
                {
                    b.HasOne("SmartSync.Domain.Entities.Residencia", null)
                        .WithMany("Comodos")
                        .HasForeignKey("ResidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSync.Domain.Entities.Dispositivo", b =>
                {
                    b.HasOne("SmartSync.Domain.Entities.Comodo", null)
                        .WithMany("Dispositivos")
                        .HasForeignKey("ComodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSync.Domain.Entities.TipoDispositivo", "TipoDispositivo")
                        .WithMany()
                        .HasForeignKey("TipoDispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDispositivo");
                });

            modelBuilder.Entity("SmartSync.Domain.Entities.Residencia", b =>
                {
                    b.HasOne("SmartSync.Domain.Entities.Usuario", null)
                        .WithMany("Residencias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSync.Domain.Entities.Comodo", b =>
                {
                    b.Navigation("Dispositivos");
                });

            modelBuilder.Entity("SmartSync.Domain.Entities.Residencia", b =>
                {
                    b.Navigation("Comodos");
                });

            modelBuilder.Entity("SmartSync.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Residencias");
                });
#pragma warning restore 612, 618
        }
    }
}
